name: Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Git tag
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag }}
      - name: Install Rust Stable
        uses: gdcorp-action-public-forks/rust-toolchain@8746a0d603bb056878fbe89fe7091bbc7aae3676
        with:
          toolchain: stable
      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # 3.3.1
        env:
          BUILD_TYPE: release
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target/
          key: cargo-${{ env.BUILD_TYPE }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ env.BUILD_TYPE }}-
      - name: Build
        run: |
          cargo build --release
          mkdir -p bin-tmp
          cp ./target/release/blog-builder bin-tmp/blog-builder-linux-x86_64

      - name: Create release
        uses: gdcorp-action-public-forks/ncipollo-release-action@d2ddde0acb4d51bbf4892910dc296ae6efdc1a13
        with: 
          tag: ${{ inputs.tag }}
          artifacts: "/bin-tmp/blog-builder-linux-x86_64"
          artifactErrorsFailBuild: true
