name: Release
on:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Generate Changelog
        run: git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%s" -i -E --grep="^(\[INTERNAL\]|\[FEATURE\]|\[FIX\]|\[DOC\])*\[FEATURE\]" > release.txt
      - name: Build Binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Compress Binary
        run: bzip2 -f target/release/blog-builder && mv target/release/blog-builder.bz2 target/release/blog-builder-x86_64-unknown-linux-gnu.bz2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release.txt
            target/release/blog-builder-x86_64-unknown-linux-gnu.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


        
