name: Release Version

on: [push]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: icepuma/rust-action@1.51.0
        with: 
          args: cargo build --release

