name: Release
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: blog-builder
            asset_name: blog-builder-linux-x86_64
          - os: macos-latest
            artifact_name: blog-builder
            asset_name: blog-builder-darwin-x86_64
          - os: windows-latest
            artifact_name: blog-builder.exe
            asset_name: blog-builder-windows-x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Build Binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
