name: Run Tests
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gdcorp-action-public-forks/rust-toolchain@8746a0d603bb056878fbe89fe7091bbc7aae3676
        with:
          toolchain: stable
      - name: Tests
        run: |
          cargo test
